{% set name = "librmm" %}
{% set version = "22.04.00" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/rapidsai/rmm/archive/refs/tags/v{{ version }}.tar.gz
    sha256: 8ea369b371b35191490d165e201101c758f272f5f3edbb042f5d376726c1c884
    folder: rmm

build:
  number: 1
  skip: true  # [(not linux) or (cuda_compiler_version == "None")]
  run_exports:
    - {{ pin_subpackage(name, max_pin="x.x") }}
  script_env:
    # for some reason /usr/local/cuda is not added to $PATH in the docker image
    - CUDA_HOME  # [ppc64le or aarch64]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}
    - cmake >=3.18
    - make
  host:
    - spdlog
    - thrust >=1.9.0
  run:
    # - spdlog >=1.8.5  # (version constraint set via run_exports)
    - thrust >=1.9.0

test:
  commands:
    - test -f $PREFIX/include/rmm/thrust_rmm_allocator.h
    - test -f $PREFIX/include/rmm/logger.hpp
    - test -f $PREFIX/include/rmm/cuda_stream.hpp
    - test -f $PREFIX/include/rmm/cuda_stream_view.hpp
    - test -f $PREFIX/include/rmm/cuda_stream_pool.hpp
    - test -f $PREFIX/include/rmm/device_uvector.hpp
    - test -f $PREFIX/include/rmm/device_scalar.hpp
    - test -f $PREFIX/include/rmm/device_buffer.hpp
    - test -f $PREFIX/include/rmm/detail/aligned.hpp
    - test -f $PREFIX/include/rmm/detail/error.hpp
    - test -f $PREFIX/include/rmm/detail/exec_check_disable.hpp
    - test -f $PREFIX/include/rmm/mr/device/detail/arena.hpp
    - test -f $PREFIX/include/rmm/mr/device/detail/free_list.hpp
    - test -f $PREFIX/include/rmm/mr/device/detail/coalescing_free_list.hpp
    - test -f $PREFIX/include/rmm/mr/device/detail/fixed_size_free_list.hpp
    - test -f $PREFIX/include/rmm/mr/device/detail/stream_ordered_memory_resource.hpp
    - test -f $PREFIX/include/rmm/mr/device/arena_memory_resource.hpp
    - test -f $PREFIX/include/rmm/mr/device/binning_memory_resource.hpp
    - test -f $PREFIX/include/rmm/mr/device/cuda_memory_resource.hpp
    - test -f $PREFIX/include/rmm/mr/device/device_memory_resource.hpp
    - test -f $PREFIX/include/rmm/mr/device/fixed_size_memory_resource.hpp
    - test -f $PREFIX/include/rmm/mr/device/limiting_resource_adaptor.hpp
    - test -f $PREFIX/include/rmm/mr/device/logging_resource_adaptor.hpp
    - test -f $PREFIX/include/rmm/mr/device/managed_memory_resource.hpp
    - test -f $PREFIX/include/rmm/mr/device/owning_wrapper.hpp
    - test -f $PREFIX/include/rmm/mr/device/per_device_resource.hpp
    - test -f $PREFIX/include/rmm/mr/device/pool_memory_resource.hpp
    - test -f $PREFIX/include/rmm/mr/device/thread_safe_resource_adaptor.hpp
    - test -f $PREFIX/include/rmm/mr/device/thrust_allocator_adaptor.hpp
    - test -f $PREFIX/include/rmm/mr/host/host_memory_resource.hpp
    - test -f $PREFIX/include/rmm/mr/host/new_delete_resource.hpp
    - test -f $PREFIX/include/rmm/mr/host/pinned_memory_resource.hpp
    - test ! -d $PREFIX/lib64

about:
  home: https://github.com/rapidsai/rmm
  license: Apache-2.0
  license_file:
    - rmm/LICENSE
  summary: RAPIDS Memory Manager

extra:
  recipe-maintainers:
    - rlratzel
    - kkraus14
    - leofang
    - jakirkham
